### ISSUE TITLE
Tomb Raider I-III Remastered save support

### ISSUE THREAD

**Issue by StenApp** [JulianOzelRose/TR-SaveMaster#2]
Hi,

how about support for the new remaster saves?

Savepath seems to be here: C:\Users\USERNAME\AppData\Roaming\TRX

[savegame.dat.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14289172/savegame.dat.txt)

Maybe you find something in the file. I play TR3, still in first level

**Comment by JulianOzelRose** [comment]
Hello,

The savegame system in Tomb Raider Remastered is quite different from classic Tomb Raider, so I am in the process of writing a new editor for TR Remastered. I've attached a primitive build of it, basically an alpha build. So far it works with TR1, Unfinished Business, and TR2. I should have the other 3 games done by the weekend and a more stable release which I'll upload as a separate repo.

Just edit the `directory.ini` to use your actual game directory, and it should work. It's a very early build and there's not much error handling, so be sure to backup your `savegame.dat` file. Let me know how it works.

[TRR-SaveMaster-v0.5.zip](https://github.com/JulianOzelRose/TR-SaveMaster/files/14298637/TRR-SaveMaster-v0.5.zip)

**Comment by xTheSolutionNOT** [comment]
Hi,

I'm getting this error when opening your alpha version
![image](https://github.com/JulianOzelRose/TR-SaveMaster/assets/160154400/e80d9097-fd15-4705-9c69-0f3b885d3e1f)

Edit: Nevermind I'm stupid, I didn't edit the directory.ini


I don't know if it's possible, but could you maybe add support for PS4 saves too? Here's a PS4 save for TR 2.

[tr2ps4save.zip](https://github.com/JulianOzelRose/TR-SaveMaster/files/14299017/tr2ps4save.zip)

The first few lines of both saves look similar but have a size difference.

Edit 2: The PS4 Save works on your editor too haha, I just had to rename the memory.dat to savegame.dat and place it into the PC save folder.

Finaledit 3: If it's not too much, here are some ideas for the editor: an option to set/reset the mission timer and for medipacks that were used would be nice, and last but not least a PC <-> PS4 save conversion. just if possible and if you have time for it :)

**Comment by JulianOzelRose** [comment]
> Edit 2: The PS4 Save works on your editor too haha, I just had to rename the memory.dat to savegame.dat and place it into the PC save folder.
> 
> Finaledit 3: If it's not too much, here are some ideas for the editor: an option to set/reset the mission timer and for medipacks that were used would be nice, and last but not least a PC <-> PS4 save conversion. just if possible and if you have time for it :)

That's very interesting that it works on PS4. It probably means that converting from PC to PS4 might be pretty doable actually, so I will look into it. I did take a look at the PS4 savegame you attached. It appears to follow the same basic structure as the PC savegame. If I had to guess, I would say this editor will end up working on PS4 for TR1 very well because most of the TR1 savegame data is static. It might have some trouble with the dynamic offsets for TR2 or TR3, but I would be interested to know how that goes once I release a more complete version.

As of right now, I'm just trying to produce a minimum viable savegame editor for TR Remastered because it's a brand new game and so there are no editors for it. Once I have that done, I will be open to feedback. I should have the first complete version by the weekend.

I forgot to mention, with TR Remastered, if you edit the `savegame.dat` file at all, you will need to restart the game for the changes to take effect because the game caches that file into memory.

**Comment by xTheSolutionNOT** [comment]
I'm happy to test the PS4 part whenever you release the updated/full version :)

**Comment by StenApp** [comment]
> Hello,
> 
> The savegame system in Tomb Raider Remastered is quite different from classic Tomb Raider, so I am in the process of writing a new editor for TR Remastered. I've attached a primitive build of it, basically an alpha build. So far it works with TR1, Unfinished Business, and TR2. I should have the other 3 games done by the weekend and a more stable release which I'll upload as a separate repo.
> 
> Just edit the `directory.ini` to use your actual game directory, and it should work. It's a very early build and there's not much error handling, so be sure to backup your `savegame.dat` file. Let me know how it works.
> 
> [TRR-SaveMaster-v0.5.zip](https://github.com/JulianOzelRose/TR-SaveMaster/files/14298637/TRR-SaveMaster-v0.5.zip)

Nice, sees my saves i did.
Looking forward for the rest of the parts.

**Comment by JulianOzelRose** [comment]
I just uploaded my TR Remastered savegame editor, you can find it [here](https://github.com/JulianOzelRose/TRR-SaveMaster/). Feel free to let me know if you encounter any issues. Just use the "Issues" page on that repo. Enjoy.
